#!/usr/bin/env bash

VERSIONS=(
    8.1.0
    7.3.0
    6.4.0
    5.5.0
    4.9.4
    4.8.5
    4.7.4
    4.6.4
    4.5.4
    4.4.7
    4.3.6
    4.2.4
    4.1.2
    4.0.4
    3.4.6
    3.3.6
    3.2.3
    3.1.1
    3.0.4
    2.95.3:oldfmt
)

if (( $# != 2 )); then
    progname=${0##*/}
    echo >&2 "USAGE: $progname <section> <target>"
    echo >&2 "For the list of sections, see, for example,"
    echo >&2 "    https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/"
    echo >&2 "EXAMPLES:"
    echo >&2 "    $progname Common-Function-Attributes.html returns_twice"
    echo >&2 "    $progname Other-Builtins.html __builtin_constant_p"
    exit 2
fi
SECTION=$1
TARGET=$2

for v in "${VERSIONS[@]}"; do
    case "$v" in
        *:oldfmt)
            pretty_v=${v%:*}
            url="https://gcc.gnu.org/onlinedocs/gcc-${pretty_v}/gcc_4.html"
            ;;
        *)
            pretty_v=$v
            url="https://gcc.gnu.org/onlinedocs/gcc-${v}/gcc/$SECTION"
            ;;
    esac
    if lynx -dump "$url" | grep -wq -- "$TARGET"; then
        echo -e "$pretty_v\tYES"
    else
        echo -e "$pretty_v\tNO"
    fi
done
