#!/usr/bin/env bash
set -e
if (( $# != 1 )); then
    echo >&2 "USAGE: ${0##*/} <magnet URL>"
    exit 2
fi
if ! [[ "$1" =~ xt=urn:btih:([^&/]+) ]]; then
    echo >&2 "E: '$1' is not a magnet URL."
    exit 1
fi
filename=meta-${BASH_REMATCH[1]}.torrent
echo "d10:magnet-uri${#1}:${1}e" > "$filename"
echo "$filename"
