#!/usr/bin/env bash

NOD_DIR=/tmp/nod-${USER?}

if [[ ! -d $NOD_DIR ]]; then
    mkdir -p -- "$NOD_DIR" || exit $?
fi

usage() {
    echo >&2 "USAGE: $0 [-n] [-t <timeout>] [-i <icon>] [-u <urgency>] [--] <appname> <summary> <body>"
    exit 2
}

# TAKES:
#     $1 — appname string
# RETURNS:
#     0 if $1 is a valid appname, non-zero otherwise
is_valid_appname() {
    [[ $1 =~ ^[0-9a-zA-Z_][-0-9a-zA-Z_]*$ ]]
}

timeout=-1
icon=
urgency=
reuse=1
while getopts 'nt:i:u:' option; do
    case "$option" in
        n) reuse=0 ;;
        t) timeout=$OPTARG ;;
        i) icon=$OPTARG ;;
        u)
            if [[ $OPTARG != [012] ]]; then
                echo >&2 "E: Ivalid urgency."
                usage
            fi
            urgency=$OPTARG
            ;;
        *) usage ;;
    esac
done
shift $(( OPTIND - 1 ))
if (( $# != 3 )); then
    usage
fi
if ! is_valid_appname "$1"; then
    echo >&2 "E: invalid appname."
    usage
fi
file=$NOD_DIR/$1
exec flock --no-fork "$file" "$BASH" -c '
unset id
(( $0 )) && read id < "$1"
d=org.freedesktop.Notifications
out=$(gdbus call --session --dest "$d" --object-path /"${d//.//}" --method "$d".Notify -- \
	"$2" "$((id))" "$3" "$4" "$5" "[]" "{${7:+"\"urgency\":<byte $7>"}}" "$6") || exit $?
[[ $out =~ ^\(uint32\ ([0-9]+),\)$ ]] || { echo >&2 "E: unexpected gdbus output: $out"; exit 1; }
echo "${BASH_REMATCH[1]}" > "$1"' "$reuse" "$file" "$1" "$icon" "$2" "$3" "$timeout" "$urgency"
