#!/usr/bin/env bash

if (( $# != 2 )); then
    echo >&2 "\
USAGE: ${0##*/} <two-letter country code> <number of exit nodes to query>
EXAMPLE: ${0##*/} ru 5"
    exit 2
fi

out=$(wget -O- https://torstatus.blutmagie.de/ \
    | sed -nr "s!.*<img[^>]*\ssrc='img/flags/([^\.]+)\.gif'[^>]*>\s*</a>\s*&nbsp;\s*<a href='router_detail\.php\?FP=([0-9a-fA-F]+).*!\1 \2!p" \
    | awk -v tgt="$1" -v lim="$2" '$1 == tgt { print $2; if(++i >= lim) exit; }')

printf '===============\n%s\n' "$out"
